# Generated by Django 3.1.2 on 2020-10-10 10:05

import datetime
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last name')),
                ('middle_name', models.CharField(max_length=50, verbose_name='Middle name')),
                ('email', models.EmailField(default='somemail@gmail.com', max_length=80, unique=True, verbose_name='Email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(default='+375333215678', max_length=128, region=None, unique=True, verbose_name='Telephone number')),
            ],
            options={
                'verbose_name': 'Follower',
                'verbose_name_plural': 'Followers',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Salary')),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
            },
        ),
        migrations.CreateModel(
            name='PostOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
            ],
            options={
                'verbose_name': 'Post office',
                'verbose_name_plural': 'Post offices',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
            },
        ),
        migrations.CreateModel(
            name='PublishingHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
            ],
            options={
                'verbose_name': 'Publishing House',
                'verbose_name_plural': 'Publishing Houses',
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Price')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='Count')),
                ('post_office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.postoffice')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.publication')),
            ],
            options={
                'verbose_name': 'Release',
                'verbose_name_plural': 'Releases',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Subscription started')),
                ('description', models.TextField(verbose_name='Description')),
                ('term', models.PositiveSmallIntegerField(default=1, verbose_name='Subscription term(month)')),
                ('end_date', models.DateField(default=datetime.date(2020, 11, 9), verbose_name='Subscription end')),
                ('post_office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.postoffice')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.release')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(verbose_name='Region Index')),
                ('post_office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.postoffice')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
            },
        ),
        migrations.AddField(
            model_name='publication',
            name='publishing_house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.publishinghouse'),
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.region')),
            ],
            options={
                'verbose_name': 'House',
                'verbose_name_plural': 'Houses',
            },
        ),
        migrations.CreateModel(
            name='Follower_Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.follower')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.subscription')),
            ],
            options={
                'verbose_name': 'Follower and Subscription',
                'verbose_name_plural': 'Followers and Subscriptions',
            },
        ),
        migrations.AddField(
            model_name='follower',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.house'),
        ),
        migrations.AddField(
            model_name='follower',
            name='subscription',
            field=models.ManyToManyField(through='home.Follower_Subscription', to='home.Subscription'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last name')),
                ('middle_name', models.CharField(max_length=50, verbose_name='Middle name')),
                ('email', models.EmailField(default='someworkmail@gmail.com', max_length=80, unique=True, verbose_name='Email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(default='+375333215378', max_length=128, region=None, unique=True, verbose_name='Telephone number')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.position')),
                ('post_office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.postoffice')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.region')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
    ]
