# Generated by Django 3.1.2 on 2020-10-19 14:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201010_1013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['pk'], 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='follower',
            options={'ordering': ['pk'], 'verbose_name': 'Follower', 'verbose_name_plural': 'Followers'},
        ),
        migrations.AlterModelOptions(
            name='follower_subscription',
            options={'ordering': ['pk'], 'verbose_name': 'Follower and Subscription', 'verbose_name_plural': 'Followers and Subscriptions'},
        ),
        migrations.AlterModelOptions(
            name='house',
            options={'ordering': ['pk'], 'verbose_name': 'House', 'verbose_name_plural': 'Houses'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['pk'], 'verbose_name': 'Position', 'verbose_name_plural': 'Positions'},
        ),
        migrations.AlterModelOptions(
            name='postoffice',
            options={'ordering': ['pk'], 'verbose_name': 'Post office', 'verbose_name_plural': 'Post offices'},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['pk'], 'verbose_name': 'Publication', 'verbose_name_plural': 'Publications'},
        ),
        migrations.AlterModelOptions(
            name='publishinghouse',
            options={'ordering': ['pk'], 'verbose_name': 'Publishing House', 'verbose_name_plural': 'Publishing Houses'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['pk'], 'verbose_name': 'Region', 'verbose_name_plural': 'Regions'},
        ),
        migrations.AlterModelOptions(
            name='release',
            options={'ordering': ['pk'], 'verbose_name': 'Release', 'verbose_name_plural': 'Releases'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['pk'], 'verbose_name': 'Subscription', 'verbose_name_plural': 'Subscriptions'},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='region',
        ),
        migrations.AddField(
            model_name='region',
            name='postman',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='home.employee'),
        ),
        migrations.AlterField(
            model_name='house',
            name='address',
            field=models.CharField(max_length=100, unique=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='postoffice',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='publishinghouse',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='region',
            name='index',
            field=models.PositiveIntegerField(unique=True, verbose_name='Region Index'),
        ),
        migrations.AlterField(
            model_name='release',
            name='post_office',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='home.postoffice'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='description',
            field=models.TextField(unique=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateField(default=datetime.date(2020, 11, 18), verbose_name='Subscription end'),
        ),
    ]
