# Generated by Django 3.1.2 on 2020-10-19 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201019_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='postman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.employee'),
        ),
    ]
