# Generated by Django 3.1.2 on 2020-10-19 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201019_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='post_office',
        ),
    ]
