# Generated by Django 3.1.2 on 2020-10-19 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_subscription_post_office'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='release',
            name='post_office',
        ),
        migrations.AddField(
            model_name='subscription',
            name='post_office',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='home.postoffice'),
        ),
    ]
