# Generated by Django 3.1.2 on 2020-10-19 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20201019_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='post_office',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='home.postoffice'),
        ),
    ]
